### ISSUE TITLE
Error on running study.optimize

### ISSUE THREAD

**Issue by mohammedaugie13** [quantumlib/OpenFermion-Cirq#340] opened 2019-03-31 23:05 UTC
I just try to run tutorial_4_variational.ipynb but when i run
`import numpy
from openfermioncirq.optimization import COBYLA, OptimizationParams, OptimizationResult
optimization_params = OptimizationParams(algorithm=COBYLA,initial_guess=[0.01])
print(study.optimize(optimization_params))`

I get the following error message:
`TypeError: ufunc 'multiply' output (typecode 'O') could not be coerced to provided output parameter (typecode 'D') according to the casting rule ''same_kind'' `

Thanks for the help.

**Comment by kevinsung** [comment] 2019-04-05 19:49
What versions of Python and OpenFermion-Cirq are you using? Any additional information to help us reproduce the error would be helpful.

**Comment by mohammedaugie13** [comment] 2019-04-06 13:49
> What versions of Python and OpenFermion-Cirq are you using? Any additional information to help us reproduce the error would be appreciated.

i using python 3.6 and openfermion-cirq 0.3.0

**Comment by vtomole** [comment] 2019-04-08 14:31
Which version of Python 3.6 specifically? This program runs fine on Python 3.6.7.

**Comment by AlexisRalli** [comment] 2019-07-04 09:41
I get the same error too. I am running:
Cirq version: 0.4.0
Openfermion version: 0.9.0
openfermionCirq version: 0.3.0

python_version:  3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0]

`ufunc multiply output (typecode O) could not be coerced to provided output parameter (typecode D) according to the casting rule same_kind`

**Comment by kevinsung** [comment] 2019-07-09 01:15
The error is caused by the notebook's use of sympy Symbols which are only present in the GitHub version of the library. In general, the notebooks are only guaranteed to execute correctly with the GitHub version of the library and not the version on PyPI. For instructions on installing the GitHub version, see the "Developer install" section on the front page: https://github.com/quantumlib/OpenFermion-Cirq.

Since this issue is not a bug I will close it.

**Closed by kevinsung** 2019-07-09 01:15 UTC

**Comment by Strilanc** [comment] 2019-07-10 00:19
This might indicate that we need a different delivery mechanism for the notebooks along with the documentation, so that they match up.
